
DEVICE = hx4k
PACKAGE = tq144
PIN_DEF = ../pins-hx4k-all.pcf

TOP = fidget
LIBRARIES = \
	busdebugger_serial.v \
	../libraries/computie_bus/computie_bus_snooper.v \
	../libraries/usart/usart_echo.v \
	../libraries/usart/usart_tx.v \
	../libraries/usart/usart_rx.v


LIBRARIES_SYNTH = \
#	../libraries/computie_bus/computie_bus_demux.sv

LIBRARIES_TEST = \

include ../common.mk

